name: main

on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Using example https://github.com/actions/starter-workflows/blob/51e3d515e95876eed0c47cd971e48fcf16c6705a/pages/static.yml
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Build 
        run: npm run build
      - name: Build GBA ENV
        run: |
          git clone https://github.com/asiekierka/wasm4-aot
          cd wasm4-aot
          git checkout 529c3e92aa0a680331a0456dc6b66d0abdc04443
          docker build -t wasm4-aot-image .
      - name: Build GBA ROM 
        run: docker run -v $PWD/build:/pwd_dir --rm wasm4-aot-image ./build.sh -f wasm2c /pwd_dir/cart.wasm gba /pwd_dir/cart
      - name: Build GBA ROM Time Scale
        run: docker run -v $PWD/build:/pwd_dir --rm wasm4-aot-image ./build.sh -f wasm2c /pwd_dir/cart.timescale.wasm gba /pwd_dir/cart.timescale
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
